### ISSUE TITLE
Reservoirs?

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas-plugins#15]
I thought the reservoirs were also implemented as a plug-in (markbakje). Did I misunderstand?

**Comment by martinvonk** [comment]
Yes, they are still here. From `pastas_plugins import reservoirs` should work.

**Comment by mbakker7** [comment]
Ah, very good @martinvonk . I found it back. Howbout the notebook with the example. Is that still somewhere? Or maybe the old notebook that I can convert to the new plugin?

**Comment by martinvonk** [comment]
I don't now if there ever was a notebook?
If I look at the original pastas branch it is not there either: 
https://github.com/pastas/pastas/compare/master...reservoir_model

**Comment by mbakker7** [comment]
Found it. Will submit PR. Closing this issue.
